Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmp65fkffn0/linux-64/pedagree-0.0.11-py36_0.tar.bz2
Adding in variants from internal_defaults
Reloading output folder: /home/vsts/conda/conda-bld
Mamba failed to solve:
 - pedagree 0.0.11.* py39_0
 - python
 - numpy
 - cython
 - cyvcf2
 - networkx
 - python

with channels:
 - file:///tmp/tmp65fkffn0

The reported errors are:
   Encountered problems while solving:
     - nothing provides requested pedagree 0.0.11.* py39_0
   

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


