Updating build index: /home/vsts/conda/conda-bld

TEST START: /tmp/tmpx3_cneoi/linux-64/smashbenchmarking-1.0.1-py27_0.tar.bz2
Adding in variants from internal_defaults
Reloading output folder: /home/vsts/conda/conda-bld
Mamba failed to solve:
 - smashbenchmarking 1.0.1.* py39_0
 - python
 - pyvcf
 - pyfasta
 - numpy
 - python

with channels:
 - file:///tmp/tmpx3_cneoi

The reported errors are:
   Encountered problems while solving:
     - nothing provides requested smashbenchmarking 1.0.1.* py39_0
   

Leaving build/test directories:
  Work:
 /home/vsts/conda/conda-bld/work 
  Test:
 /home/vsts/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/vsts/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh 
  Build:
source activate  /home/vsts/conda/conda-bld/_build_env 


